- type: entity
  abstract: true
  id: BaseMutation
  components:
  - type: Mutation

- type: entity
  abstract: true
  parent: BaseMutation
  id: BaseFreeMutation
  components:
  - type: Mutation
    instability: 0

# prevents a mutation from triggering if the mutated mob is dead
- type: entity
  abstract: true
  parent: BaseMutation
  id: BaseTriggerMutation
  components:
  - type: GenericTriggerCondition
    condition: !type:MutatedNestedCondition
      condition: !type:MobStateCondition
        inverted: true
        mobstate: Dead

- type: entity
  abstract: true
  parent: BaseAction
  id: BaseMutationAction
  components:
  - type: Action
    itemIconStyle: BigAction # mutations don't have sprites, only show the action icon
    raiseOnAction: true # don't want to shit up the body entity with a bunch of action related components
